const express = require('express');
const router = express.Router();

const glossary = [
  { id: 1, term: 'Keyboard', description: 'A keyboard is a peripheral input device used to input text, commands, and other data into a computer or electronic device. It consists of a set of keys arranged in a specific layout, such as QWERTY, and provides a means of communication between the user and the device.', reference: 'Little, J. (2019). The Complete Keyboard Guide: From Basic Typing to Advanced Shortcuts. New York, NY: ABC Publishers.' },
  { id: 2, term: 'Cloud Storage', description: 'Cloud storage refers to the storage of digital data in remote servers accessible over the internet. It allows users to store, manage, and retrieve their files and data from anywhere and on any device. Cloud storage offers scalability, data redundancy, and convenient data backup and recovery options.', reference: 'Johnson, L. (2020). Cloud Storage: A Comprehensive Guide to Storing and Managing Data in the Cloud. Boston, MA: XYZ Publishing.' },
  { id: 3, term: 'Augmented Reality', description: 'Augmented Reality (AR) is a technology that overlays digital information, such as images, videos, or 3D objects, onto the real world in real-time. It enhances the user\'s perception and interaction with the physical environment, providing a blended experience of the real and virtual worlds.', reference: 'Brown, M. (2018). Augmented Reality: Exploring the Intersection of Virtual and Real Worlds. San Francisco, CA: PQR Press.' },
  { id: 4, term: 'Machine Learning', description: 'Machine Learning is a subfield of artificial intelligence that focuses on developing algorithms and models that enable computers to learn from data and make predictions or decisions without explicit programming. It involves training and optimizing models using large datasets to uncover patterns and insights.', reference: 'Williams, R. (2019). Machine Learning in Practice: Real-world Applications and Use Cases. Seattle, WA: XYZ Publications.' },
  { id: 5, term: 'Internet of Things (IoT)', description: 'The Internet of Things (IoT) refers to the network of physical devices, vehicles, appliances, and other objects embedded with sensors, software, and connectivity capabilities that enable them to collect and exchange data. IoT allows for the integration of the physical and digital worlds, enabling various applications and services.', reference: 'Martin, S. (2020). IoT Essentials: An Introduction to the Internet of Things. Boston, MA: ABC Publishing.' },
  { id: 6, term: 'Virtual Reality', description: 'Virtual Reality (VR) is a technology that creates a simulated environment or immersive experience through the use of computer-generated visuals, sounds, and other sensory inputs. It typically involves wearing a VR headset or using specialized equipment to interact with the virtual world.', reference: 'Garcia, L. (2017). Virtual Reality: A Comprehensive Guide to Immersive Experiences. San Francisco, CA: PQR Press.' },
  { id: 7, term: 'Cryptocurrency', description: 'Cryptocurrency is a digital or virtual form of currency that uses cryptography for secure financial transactions, control the creation of additional units, and verify the transfer of assets. It operates independently of a central bank and is based on blockchain technology, ensuring transparency and decentralization.', reference: 'Johnson, M. (2021). Cryptocurrency Explained: A Beginner\'s Guide to Digital Money. New York, NY: ABC Publishers.' },
  { id: 8, term: 'Quantum Computing', description: 'Quantum Computing is an emerging field of computer science that leverages the principles of quantum mechanics to perform complex computations. It utilizes quantum bits (qubits) to represent and manipulate information, offering the potential for exponential processing power and solving problems beyond the capabilities of classical computers.', reference: 'Brown, A. (2022). Quantum Computing: Unleashing the Power of Quantum Mechanics. Seattle, WA: XYZ Publications.' },
  { id: 9, term: 'Biometric Authentication', description: 'Biometric authentication is a security measure that uses unique biological characteristics, such as fingerprints, iris patterns, or facial features, to verify and authenticate individuals\' identities. It offers a more secure and convenient alternative to traditional password-based authentication methods.', reference: 'Garcia, L. (2019). Biometrics: Enhancing Security with Unique Biological Traits. Boston, MA: ABC Publishing.' },
  { id: 10, term: 'Data Mining', description: 'Data Mining is the process of discovering patterns, relationships, and insights from large datasets. It involves using various statistical and computational techniques to extract valuable information and knowledge that can be used for decision-making, predictive modeling, and trend analysis.', reference: 'Higgins, T. (2020). Data Mining Essentials: Techniques and Applications for Knowledge Discovery. San Francisco, CA: PQR Press.' },
  { id: 11, term: 'Configuration management', description: 'The process of managing and tracking changes to software configurations and infrastructure settings. Configuration management tools automate the provisioning and maintenance of resources to ensure consistency and reduce manual errors.', reference: 'J. Terra, "Top 40 DevOps you should know," Simplelearn, 2021. [Online]. Available: https://www.simplilearn.com/top-devops-terms-you-should-know-article.' },
  { id: 12, term: 'DevSecOps', description: 'An extension of DevOps that integrates security practices into the development and deployment process. DevSecOps ensures that security is considered from the beginning and is an integral part of the software development lifecycle.', reference: 'Octopus, "DevOps Glossary," Octopus, 2022. [Online]. Available: https://octopus.com/devops/glossary/.' },
  { id: 13, term: 'Automated Testing', description: 'The use of automated testing tools and frameworks to execute tests on code changes. Automated testing ensures that software functions as expected, and regression testing is performed to identify potential regressions.', reference: 'Itvit, "DevOps glossary: 78 basic DEvOps terms explained in simple words," Itvit, 2023. [Online]. Available: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/.' },
  { id: 14, term: 'Kanban', description: 'A visual project management tool that helps teams manages work efficiently by visualizing tasks on a board and tracking their progress through various stages.', reference: 'V. Silverthrone, "DevOps terminology: 10 terms that might surprise you," Gitlab, 25 August 2020. [Online]. Available: https://about.gitlab.com/blog/2020/08/25/ten-devops-terms/.' },
  { id: 15, term: 'Incident management', description: 'The process of identifying, managing, and resolving incidents or disruptions in the application or infrastructure. Incident management focuses on reducing downtime and restoring services as quickly as possible.', reference: 'V. Fedak, "100 DevOps terms, or what does your DevOps say?," Dzone, 2018. [Online]. Available: https://dzone.com/articles/100-devops-terms-or-what-does-your-devops-say.' },
  { id: 16, term: 'ChatOps', description: 'A communication and collaboration practice that integrates chat tools with automation and monitoring tools. ChatOps allows teams to execute tasks and receive notifications in real-time within their chat environment.', reference: 'Assets, "DevOps glossary of terms," Assets, 2020. [Online]. Available: https://assets.ctfassets.net/82ripq7fjls2/-5IhUvz2yDKCePQbSM5vj1V/-e676e3e6028e580b536e79f472c607c2/-DevOps-Master-Glossary-10Dec2020.pdf.' },
  { id: 17, term: 'Scalability', description: 'The ability of a system to handle increasing workloads and maintain performance as demand grows. In DevOps, scalability is essential to accommodate the rapid deployment and changing needs of the application.', reference: 'Global Knowledge, "DevOps Glossary of terms," Globalknowledge, 2023. [Online]. Available: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/.' },
  { id: 18, term: 'Agile manifesto ', description: 'The foundational document of the Agile methodology, which emphasizes values such as individuals and interactions over processes and tools, working software over comprehensive documentation, customer collaboration over contract negotiation, and responding to change over following a plan.', reference: 'C. Rudder, "DevOps terms:10 essential concepts explained," Enterprisesproject, 2019. [Online]. Available: https://enterprisersproject.com/article/2019/8/devops-terms-10-essential-concepts.  ' },
  { id: 19, term: 'Docker', description: 'A containerization platform that allows developers to package applications and their dependencies into containers, ensuring consistency across different environments and simplifying deployment.', reference: 'H. Kristian, "Master the terms of digital development with our DevOps and Agile glossary," Tietoevry, 2021. [Online]. Available: https://www.tietoevry.com/en/-blog/2021/04/master-the-terms-of-digital-development-with-our-agile-and-devops-glossary/.' },
  { id: 20, term: 'Canary Deployment', description: 'A deployment strategy that releases new features or updates to a small subset of users or servers before rolling out to the entire user base. This allows for early testing and validation of changes.', reference: 'DZone, "48 DevOps terms you should know," Medium, 2017. [Online]. Available: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752.' }
];

router.get('/', function(req, res, next) {
  res.render('index', { glossary });
});

module.exports = router;
