const express = require('express');
const router = express.Router();

const glossary = [
  { id: 1, term: 'Keyboard', description: 'A keyboard is a peripheral input device used to input text, commands, and other data into a computer or electronic device. It consists of a set of keys arranged in a specific layout, such as QWERTY, and provides a means of communication between the user and the device.', reference: 'Little, J. (2019). The Complete Keyboard Guide: From Basic Typing to Advanced Shortcuts. New York, NY: ABC Publishers.' },
  { id: 2, term: 'Cloud Storage', description: 'Cloud storage refers to the storage of digital data in remote servers accessible over the internet. It allows users to store, manage, and retrieve their files and data from anywhere and on any device. Cloud storage offers scalability, data redundancy, and convenient data backup and recovery options.', reference: 'Johnson, L. (2020). Cloud Storage: A Comprehensive Guide to Storing and Managing Data in the Cloud. Boston, MA: XYZ Publishing.' },
  { id: 3, term: 'Augmented Reality', description: 'Augmented Reality (AR) is a technology that overlays digital information, such as images, videos, or 3D objects, onto the real world in real-time. It enhances the user\'s perception and interaction with the physical environment, providing a blended experience of the real and virtual worlds.', reference: 'Brown, M. (2018). Augmented Reality: Exploring the Intersection of Virtual and Real Worlds. San Francisco, CA: PQR Press.' },
  { id: 4, term: 'Machine Learning', description: 'Machine Learning is a subfield of artificial intelligence that focuses on developing algorithms and models that enable computers to learn from data and make predictions or decisions without explicit programming. It involves training and optimizing models using large datasets to uncover patterns and insights.', reference: 'Williams, R. (2019). Machine Learning in Practice: Real-world Applications and Use Cases. Seattle, WA: XYZ Publications.' },
  { id: 5, term: 'Internet of Things (IoT)', description: 'The Internet of Things (IoT) refers to the network of physical devices, vehicles, appliances, and other objects embedded with sensors, software, and connectivity capabilities that enable them to collect and exchange data. IoT allows for the integration of the physical and digital worlds, enabling various applications and services.', reference: 'Martin, S. (2020). IoT Essentials: An Introduction to the Internet of Things. Boston, MA: ABC Publishing.' },
  { id: 6, term: 'Virtual Reality', description: 'Virtual Reality (VR) is a technology that creates a simulated environment or immersive experience through the use of computer-generated visuals, sounds, and other sensory inputs. It typically involves wearing a VR headset or using specialized equipment to interact with the virtual world.', reference: 'Garcia, L. (2017). Virtual Reality: A Comprehensive Guide to Immersive Experiences. San Francisco, CA: PQR Press.' },
  { id: 7, term: 'Cryptocurrency', description: 'Cryptocurrency is a digital or virtual form of currency that uses cryptography for secure financial transactions, control the creation of additional units, and verify the transfer of assets. It operates independently of a central bank and is based on blockchain technology, ensuring transparency and decentralization.', reference: 'Johnson, M. (2021). Cryptocurrency Explained: A Beginner\'s Guide to Digital Money. New York, NY: ABC Publishers.' },
  { id: 8, term: 'Quantum Computing', description: 'Quantum Computing is an emerging field of computer science that leverages the principles of quantum mechanics to perform complex computations. It utilizes quantum bits (qubits) to represent and manipulate information, offering the potential for exponential processing power and solving problems beyond the capabilities of classical computers.', reference: 'Brown, A. (2022). Quantum Computing: Unleashing the Power of Quantum Mechanics. Seattle, WA: XYZ Publications.' },
  { id: 9, term: 'Biometric Authentication', description: 'Biometric authentication is a security measure that uses unique biological characteristics, such as fingerprints, iris patterns, or facial features, to verify and authenticate individuals\' identities. It offers a more secure and convenient alternative to traditional password-based authentication methods.', reference: 'Garcia, L. (2019). Biometrics: Enhancing Security with Unique Biological Traits. Boston, MA: ABC Publishing.' },
  { id: 10, term: 'Data Mining', description: 'Data Mining is the process of discovering patterns, relationships, and insights from large datasets. It involves using various statistical and computational techniques to extract valuable information and knowledge that can be used for decision-making, predictive modeling, and trend analysis.', reference: 'Higgins, T. (2020). Data Mining Essentials: Techniques and Applications for Knowledge Discovery. San Francisco, CA: PQR Press.' },
  { id: 11, term: 'Configuration management', description: 'The process of managing and tracking changes to software configurations and infrastructure settings. Configuration management tools automate the provisioning and maintenance of resources to ensure consistency and reduce manual errors.', reference: 'J. Terra, "Top 40 DevOps you should know," Simplelearn, 2021. [Online]. Available: https://www.simplilearn.com/top-devops-terms-you-should-know-article.' },
  { id: 12, term: 'DevSecOps', description: 'An extension of DevOps that integrates security practices into the development and deployment process. DevSecOps ensures that security is considered from the beginning and is an integral part of the software development lifecycle.', reference: 'Octopus, "DevOps Glossary," Octopus, 2022. [Online]. Available: https://octopus.com/devops/glossary/.' },
  { id: 13, term: 'Automated Testing', description: 'The use of automated testing tools and frameworks to execute tests on code changes. Automated testing ensures that software functions as expected, and regression testing is performed to identify potential regressions.', reference: 'Itvit, "DevOps glossary: 78 basic DEvOps terms explained in simple words," Itvit, 2023. [Online]. Available: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/.' },
  { id: 14, term: 'Kanban', description: 'A visual project management tool that helps teams manages work efficiently by visualizing tasks on a board and tracking their progress through various stages.', reference: 'V. Silverthrone, "DevOps terminology: 10 terms that might surprise you," Gitlab, 25 August 2020. [Online]. Available: https://about.gitlab.com/blog/2020/08/25/ten-devops-terms/.' },
  { id: 15, term: 'Incident management', description: 'The process of identifying, managing, and resolving incidents or disruptions in the application or infrastructure. Incident management focuses on reducing downtime and restoring services as quickly as possible.', reference: 'V. Fedak, "100 DevOps terms, or what does your DevOps say?," Dzone, 2018. [Online]. Available: https://dzone.com/articles/100-devops-terms-or-what-does-your-devops-say.' },
  { id: 16, term: 'ChatOps', description: 'A communication and collaboration practice that integrates chat tools with automation and monitoring tools. ChatOps allows teams to execute tasks and receive notifications in real-time within their chat environment.', reference: 'Assets, "DevOps glossary of terms," Assets, 2020. [Online]. Available: https://assets.ctfassets.net/82ripq7fjls2/-5IhUvz2yDKCePQbSM5vj1V/-e676e3e6028e580b536e79f472c607c2/-DevOps-Master-Glossary-10Dec2020.pdf.' },
  { id: 17, term: 'Scalability', description: 'The ability of a system to handle increasing workloads and maintain performance as demand grows. In DevOps, scalability is essential to accommodate the rapid deployment and changing needs of the application.', reference: 'Global Knowledge, "DevOps Glossary of terms," Globalknowledge, 2023. [Online]. Available: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/.' },
  { id: 18, term: 'Agile manifesto ', description: 'The foundational document of the Agile methodology, which emphasizes values such as individuals and interactions over processes and tools, working software over comprehensive documentation, customer collaboration over contract negotiation, and responding to change over following a plan.', reference: 'C. Rudder, "DevOps terms:10 essential concepts explained," Enterprisesproject, 2019. [Online]. Available: https://enterprisersproject.com/article/2019/8/devops-terms-10-essential-concepts.  ' },
  { id: 19, term: 'Docker', description: 'A containerization platform that allows developers to package applications and their dependencies into containers, ensuring consistency across different environments and simplifying deployment.', reference: 'H. Kristian, "Master the terms of digital development with our DevOps and Agile glossary," Tietoevry, 2021. [Online]. Available: https://www.tietoevry.com/en/-blog/2021/04/master-the-terms-of-digital-development-with-our-agile-and-devops-glossary/.' },
  { id: 20, term: 'Canary Deployment', description: 'A deployment strategy that releases new features or updates to a small subset of users or servers before rolling out to the entire user base. This allows for early testing and validation of changes.', reference: 'DZone, "48 DevOps terms you should know," Medium, 2017. [Online]. Available: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752.' },
  { id: 21, term: 'Container registry', description: 'The container registry is known to be a key component that supports Docker and also serves for container images as a sink to be produced using pipelines and for container deployments as a source. A container registry is used to distribute lots of images when the customers use and they include databases, operating systems, cluster deployment setups, etc. ', reference: 'Anwar, A. (2018). Improving Docker Registry Design based on Production Workload Analysis. 16th USENIX Conference on File and Storage Technologies, 265-278.' },
  { id: 22, term: 'Git', description: 'Git is a DevOps tool that is mainly used for source code management. It is an open-source and free version control system that is used for efficiently handling projects.  This Git is highly used in tracking the changes that come in source code and it is enabled with multiple developers working together. ', reference: 'Perez-Riverol, Y. (2016). Ten Simple Rules for Taking Advantage of Git and GitHub. PLoS Computational Biology, 1-11.' },
  { id: 23, term: 'Microsoft Azure ', description: 'Microsoft Azure is an infrastructure and a popular cloud service platform which used to offer SaaS, PaaS, and IaaS which have scalability, high reliability, and it has low-cost infrastructure. Azure offers some services for customers with a virtual machine, SQL database, virtual network, Windows Azure name resolution, scheduler, traffic manager, and content delivery network. ', reference: 'Rizik M. H, A.-S. (2019). An Investigation of Microsoft Azure and Amazon Web Services from Users’ Perspectives. International Journal of Emerging Technologies in Learning (iJET) , 217-241.' },
  { id: 24, term: 'Docker compose', description: 'Docker Compose helps in organizing a group of containers. There is a set of docker containers that is specified in the YAML configuration file and it is used to override the runtime configuration of the containers. It allows for creating and running with a multi-container for docker applications. It helps in defining and sharing multi-container applications. ', reference: 'Raj, A. (2021). Building Microservices with Docker Compose. The International journal of analytical and experimental modal analysis, 1215-1219.' },
  { id: 25, term: 'Project Management', description: 'Project management is known as specific knowledge uses, tools, techniques, and skills that are used to deliver a thing with people’s value. Software development is improved with the process of business, building construction, and the relief that comes after a disaster.  It is an act with a plan, organized, and the project is managed in achievement for an outcome.', reference: 'Shawl, S. (2016). Establishing an effective project management and control system in project based organizations. best: International Journal of Humanities, Arts, Medicine and Sciences (BEST: IJHAMS), 23-32.' },
  { id: 26, term: 'Information technology', description: 'Information technology is the use of computers which used to create, store, process, retrieve, and exchange every type of information and data. It helps in accessing the information and they are responsible for a large portion of the business operations, and working force and it has personal access to a piece of information which is comprised of everyday activities. ', reference: 'Berisha-Shaqiri, A. (2015). Impact of Information Technology and Internet in Businesses. Academic Journal of Business, Administration, Law and Social Sciences, 73-79.' },
  { id: 27, term: 'GitHub repository', description: 'GitHub is one of the leading platforms that has open-source software projects. GitHub is facilitated by many developers that used to collaborate and contribute to the projects with a performance in several actions like updating the projects using the commit history, logging issues or the defects using reports, and contributing to the projects in pull requests.  ', reference: 'Sciences (BEST: IJHAMS), 23-32. Venigalla, A. S. (2021). Whats in a GitHub Repository? -- A Software Documentation Perspective. arXiv, 1-11.' },
  { id: 28, term: 'Node.js', description: 'Node.js is referred to as JavaScript in a running environment.  It has been built over a Chrome V8 JavaScript engine and is a cross-platform running environment. Using the node, it can be easy to build fast, scalable, and lightweight applications. Node.js allows JavaScript to be used end to end which is on the client and the server end. ', reference: 'Jadhav, G. (2020). Role of Node.js in Modern Web Application Development . International Research Journal of Engineering and Technology (IRJET) , 6145-6150.' },
  { id: 29, term: 'Dockerize microservice', description: 'The Dockerize microservices are used for building decentralized architectures. The docker containers are required with a few computing resources which is more than the virtual machines. This Docker is very possible in reduction of the performance overhead and they deployed with many microservices on the same server.', reference: 'Wan, X. (2018). Application deployment using Microservice and Docker containers: Framework and optimization. Journal of Network and Computer Applications, 97-109. Database server' },
  { id: 30, term: 'Database Servers', description: 'Database servers are referred to as network computers which are on the network that is to be dedicated to the storage of the database and the retrieval of the data that comes from the database. It consists of software and hardware used in running a database. Oracle, and Microsoft SQL servers are some examples. ', reference: 'Setiyadi, A. (2018). Information System Monitoring Access Log Database on Database Server. IOP Conference Series Materials Science and Engineering, 1-10.' }
];

router.get('/', function(req, res, next) {
  res.render('index', { glossary });
});

module.exports = router;
